title: STUnD
author: 
  name: Arianna Masciolini
  email: arianna.masciolini@gmail.com

description: > 
  A Search Tool for (parallel) Universal Dependencies treebanks that runs in your browser.

header_pages:
  - tutorial.md
  - installation.md
  - pub.md

show_excerpts: false

remote_theme: "jekyll/minima@1e8a445"

minima:
  skin: dark
  date_format: "%-d %B %Y"
  social_links:
    - { platform: github, user_url: https://github.com/harisont }
    - { platform: instagram, user_url: https://www.instagram.com/unottica/ }
    - { platform: youtube, user_url: https://www.youtube.com/c/ImparalHaskellemettilodaparte }

plugins:
  - jekyll-feed